modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="palix"
version="1.3.7"
displayName="Palix"
credits="Created using MCreator Thank youuu"
displayURL="https://www.curseforge.com/minecraft/mc-mods/palix"
logoFile="logo.png"
authors="OH64"
description='''
Everything is made with palix
'''

[[dependencies.palix]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




